name: Urban Dev
description: Code and beyond
avatar: 'http://andrzejurban.github.io/assets/images/profile.png'
meta_description: "Urban Dev, Code and beyond"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'http://andrzejurban.github.io'
# google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://andrzejurban.github.io'
author:         'Andrzej Urban'

footer-links:
    twitter: andrzejurb
    github: urbanand
